### ISSUE TITLE
Data Error while running this code

### ISSUE THREAD

**Issue by irondeep** [lafkpages/FreericeHack#1]
```
Traceback (most recent call last):
  File "c:\Users\x\Downloads\Request.py", line 198, in <module>
    freerice.newGame()
  File "c:\Users\x\Downloads\Freerice.py", line 117, in newGame
    self.answer_url = data['data']['links']['self']
KeyError: 'data'
```

Can you fix it?

**Comment by lafkpages** [comment]
Did that happen immediately after running the code or after a while?
If it happened a while after running the code then there's nothing you can do. It means that you are getting so much rice so fast that the Freerice servers have to temporarily block you. All you can do is wait until you get unblocked, or make it send the requests at a slower rate to avoid blocking.
Read this as well: [429 Too Many Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429)

**Comment by lafkpages** [comment]
I have updated the code to not show an error and show a useful message instead. Also, I've added the option to make it slower to avoid blocking, check the note at the end of the [PyRice bot in the README](https://github.com/lafkpages/FreericeHack/blob/main/README.md#pyrice-python3)

**Comment by irondeep** [comment]
Yes it is showing after running for some time..

Well Updated instructions of Readme is Showing Argument parsing error.

**Comment by lafkpages** [comment]
That means you are writing the command wrong.

For example, if you want it to pause for 5 seconds per question, you would do:
`python3 Requester.py -i 5`

To use it with your user ID:
`python3 Requester.py -u your-user-id -i 5`

I found that the minimum you can do is 4 seconds per question, any lower you would get blocked.
